# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QJqbXfBnKgXXHT3zF4oLZ5gpDSONPhSy
"""

#3.4 손실 함수

#평균 제곱오차

import torch
from torch import nn

y=torch.tensor([3.0,3.0,3.0,3.0,3.0])   # 출력
t=torch.tensor([2.0,2.0,2.0,2.0,2.0])   # 정답

loss_func = nn.MSELoss() # 평균 제곱 오차
loss = loss_func(y,t)
print(loss.item())

import torch
from torch import nn

# 소프트맥스 함수로의 입력
x = torch.tensor([[1.0,2.0,3.0],   # 입력 1
                  [3.0,1.0,2.0]]   # 입력 2
                  )

# 정답 (one-hot 표현에서 1의 위치)
t = torch.tensor([2,   # 입력 1에 대응하는 정답)
                  0])  # 입력 2에 대응하는 정답)

loss_func = nn.CrossEntropyLoss()  # 소프트맥스 함수 + 교차 엔트로피 오차
loss = loss_func(x,t)
print(loss.item())