/*STREAM 예제
  스트림을 생성 하면 그 시점으로 부터 
  새롭게 DML 한 내용만 남겨 보인다. 
*/

USE ROLE SYSADMIN;

USE DATABASE CITIBIKE;


CREATE OR REPLACE TABLE BRANCH 
(
     ID       varchar
,    City     varchar
,    Amount   number(20,0)
);

INSERT INTO BRANCH VALUES(1201, 'A', 5387.9);
INSERT INTO BRANCH VALUES(1202, 'B', 5387.9);
INSERT INTO BRANCH VALUES(1203, 'C', 5387.9);

SELECT * FROM BRANCH;

CREATE OR REPLACE STREAM STREAM_A ON TABLE BRANCH;
CREATE OR REPLACE STREAM STREAM_B ON TABLE BRANCH;

SHOW STREAMS;

SELECT * FROM STREAM_A;
SELECT * FROM STREAM_B;

INSERT INTO BRANCH VALUES(1204, 'D', 6387.9);
INSERT INTO BRANCH VALUES(1205, 'E', 6387.9);
INSERT INTO BRANCH VALUES(1206, 'F', 6387.9);

SELECT * FROM BRANCH;
SELECT * FROM STREAM_A;
SELECT * FROM STREAM_B;

DELETE FROM BRANCH WHERE ID = 1205;








