/*서브쿼리 */

USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;
CREATE OR REPLACE DATABASE SUBQUERIES;

CREATE OR REPLACE SCHEMA SUBQUERIES;

CREATE OR REPLACE TABLE SUBQUERIES.SUBQUERIES.DERIVERD
(
     ID     integer
,    AMT    integer
,    Total  integer
);

INSERT INTO DERIVERD  VALUES(1,1000,4000);
INSERT INTO DERIVERD  VALUES(2,2000,2000);
INSERT INTO DERIVERD  VALUES(3,3000,3200);
INSERT INTO DERIVERD  VALUES(4,4000,7400);
INSERT INTO DERIVERD  VALUES(5,5000,2700);
INSERT INTO DERIVERD  VALUES(6,6000,9000);

SELECT * FROM  DERIVERD;


CREATE OR REPLACE TABLE SUBQUERIES.SUBQUERIES.DERIVERD_2
(
     ID     integer
,    AMT    integer
,    Total  integer
);


INSERT INTO DERIVERD_2  VALUES(1,1010,100);
INSERT INTO DERIVERD_2  VALUES(2,2010,100);
INSERT INTO DERIVERD_2  VALUES(3,3010,200);
INSERT INTO DERIVERD_2  VALUES(4,4010,400);
INSERT INTO DERIVERD_2  VALUES(5,5010,700);
INSERT INTO DERIVERD_2  VALUES(6,6010,300);


SELECT  *
FROM    DERIVERD
WHERE  1=1
AND    ID = (SELECT MIN(ID) FROM DERIVERD_2 )
;


WITH CTE 
AS
(
  SELECT MIN(ID) AS ID FROM DERIVERD_2 
)
SELECT *
FROM   DERIVERD
WHERE  1=1
AND    ID = (SELECT ID FROM CTE);




