/*객체 만들기 */
USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;

/*WAREHOUSE 생성 */
CREATE OR REPLACE WAREHOUSE VW1_WH WITH WAREHOUSE_SIZE = 'X-SMALL'
INITIALLY_SUSPENDED = true;
CREATE OR REPLACE WAREHOUSE VW2_WH WITH WAREHOUSE_SIZE = 'X-SMALL'
INITIALLY_SUSPENDED = true;
CREATE OR REPLACE WAREHOUSE VW3_WH WITH WAREHOUSE_SIZE = 'X-SMALL'
INITIALLY_SUSPENDED = true;

/*WAREHOUSE 확인 */
SHOW WAREHOUSES;

/* 권한에 따른 데이터 베이스 확인 */
USE ROLE SYSADMIN; 
SHOW DATABASES;

USE ROLE PUBLIC;
SHOW DATABASES;

USE ROLE ACCOUNTADMIN;
SHOW DATABASES;

/* 수키마 만들기 */

USE ROLE SYSADMIN;
CREATE OR REPLACE DATABASE DB1;
CREATE OR REPLACE DATABASE DB2;

CREATE OR REPLACE SCHEMA DB2_SCHEMA1;
CREATE OR REPLACE SCHEMA DB2_SCHEMA2;
CREATE OR REPLACE SCHEMA DB1.DB1_sCHEMA1;

SHOW DATABASES;


/* 리소스 모니터를 만드는 쿼리 */
USE ROLE ACCOUNTADMIN;    -- ACCOUNTADMIN 권한으로만 가능
CREATE OR REPLACE RESOURCE MONITOR MONITOR1_RM WITH CREDIT_QUOTA =1000
TRIGGERS 
ON 75 PERCENT DO NOTIFY
ON 98 PERCENT DO SUSPEND 
ON 105 PERCENT DO SUSPEND_IMMEDIATE;

SHOW RESOURCE MONITORS;



/* 사용자 생성 */
USE ROLE USERADMIN; 
CREATE OR REPLACE USER USER1 LOGIN_NAME = ARNOLD;
CREATE OR REPLACE USER USER2 LOGIN_NAME = BEATRICE;
CREATE OR REPLACE USER USER3 LOGIN_NAME = COLLIN;
CREATE OR REPLACE USER USER4 LOGIN_NAME = DIEDRE;


USE ROLE USERADMIN;
SHOW USERS; 

USE ROLE SECURITYADMIN; 
SHOW USERS;


/* USERADMIN 역할 확인*/
USE ROLE USERADMIN;
SHOW ROLES;

/* ROLL 생성 */

USE ROLE USERADMIN;
CREATE OR REPLACE ROLE DATA_SCIENTIST;
CREATE OR REPLACE ROLE ANALYST_SR;
CREATE OR REPLACE ROLE ANALYST_JR;
CREATE OR REPLACE ROLE DATA_EXCHANGE_ASST;
CREATE OR REPLACE ROLE ACCOUNTANT_SR;
CREATE OR REPLACE ROLE ACCOUNTANT_JR;
CREATE OR REPLACE ROLE PRD_DBA;
CREATE OR REPLACE ROLE DATA_ENGINEER;
CREATE OR REPLACE ROLE DEVELOPER_SR;
CREATE OR REPLACE ROLE DEVELOPER_JR;
SHOW ROLES;

/** 시스템 수준 서비스 계정 및 액세스 역할*/
/* 시스템 서비스 계정 역할 생성*/
USE ROLE USERADMIN;
CREATE OR REPLACE ROLE LOADER;
CREATE OR REPLACE ROLE VISUALIZER;
CREATE OR REPLACE ROLE REPORTING;
CREATE OR REPLACE ROLE MONITORING;

/*시스템 객체 액세스 역할을 생성*/
USE ROLE USERADMIN;
CREATE OR REPLACE ROLE DB1_SCHEMA1_READONLY;
CREATE OR REPLACE ROLE DB1_SCHEMA1_ALL;
CREATE OR REPLACE ROLE DB2_SCHEMA1_READONLY;
CREATE OR REPLACE ROLE DB2_SCHEMA1_ALL;
CREATE OR REPLACE ROLE DB2_SCHEMA2_READONLY;
CREATE OR REPLACE ROLE DB2_SCHEMA2_ALL;

CREATE OR REPLACE ROLE RM1_MODIFY;

CREATE OR REPLACE ROLE WH1_USAGE;
CREATE OR REPLACE ROLE WH2_USAGE;
CREATE OR REPLACE ROLE WH3_USAGE;

CREATE OR REPLACE ROLE  DB1_MONITOR;
CREATE OR REPLACE ROLE  DB2_MONITOR;
CREATE OR REPLACE ROLE  WH1_MONITOR;
CREATE OR REPLACE ROLE  WH2_MONITOR;
CREATE OR REPLACE ROLE  WH3_MONITOR;
CREATE OR REPLACE ROLE  RM1_MONITOR;


/*역할 계층 할당 : 다른 역할에 역할 할당 */
USE ROLE USERADMIN;

GRANT ROLE RM1_MONITOR TO ROLE MONITORING;
GRANT ROLE WH1_MONITOR TO ROLE MONITORING;
GRANT ROLE WH2_MONITOR TO ROLE MONITORING;
GRANT ROLE WH3_MONITOR TO ROLE MONITORING;
GRANT ROLE DB1_MONITOR TO ROLE MONITORING;
GRANT ROLE DB2_MONITOR TO ROLE MONITORING;
GRANT ROLE WH3_USAGE TO ROLE MONITORING;

GRANT ROLE DB1_SCHEMA1_ALL TO ROLE LOADER;
GRANT ROLE DB2_SCHEMA1_ALL TO ROLE LOADER;
GRANT ROLE DB2_SCHEMA2_ALL TO ROLE LOADER;
GRANT ROLE WH3_USAGE TO ROLE LOADER;

GRANT ROLE DB2_SCHEMA1_READONLY TO ROLE VISUALIZER;
GRANT ROLE DB2_SCHEMA2_READONLY TO ROLE VISUALIZER;
GRANT ROLE WH3_USAGE TO ROLE VISUALIZER;

GRANT ROLE DB1_SCHEMA1_READONLY TO ROLE REPORTING;
GRANT ROLE DB2_SCHEMA1_READONLY TO ROLE REPORTING;
GRANT ROLE DB2_SCHEMA2_READONLY TO ROLE REPORTING;
GRANT ROLE WH3_USAGE TO ROLE REPORTING;


/*역할에 권한 부여 ACCOUNTADMIN만 가능 */
USE ROLL ACCOUNTADMIN;
GRANT CREATE DATA EXCHANGE LISTING ON ACCOUNT TO ROLE DATA_EXHANGE_ASST;
GRANT IMPORT SHARE ON ACCOUNT TO ROLE DATA_EXHANGE_ASST;
GRANT CREATE SHARE ON ACCOUNT TO ROLE DATA_EXHANGE_ASST;

GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE MONITORING;
GRANT MONITOR ON RESOURCE MONITOR MONITOR1_RM TO ROLE MONITORING;
GRANT MONITOR USAGE ON ACCOUNT TO ROLE ACCOUNTANT_JR;
GRANT APPLY MASKING POLICY ON ACCOUNT TO ROLE ACCOUNTANT_SR;
GRANT MONITOR EXECUTION ON ACCOUNT TO ROLE ACCOUNTANT_SR;
GRANT MODIFY ON RESOURCE MONITOR MONITOR1_RM TO ROLE ACCOUNTANT_SR;


/* 사용자에게 역할 할당 */
USE ROLE USERADMIN;

GRANT ROLE DATA_EXCHANGE_ASST TO USER USER1;
GRANT ROLE DATA_SCIENTIST TO USER USER2;
GRANT ROLE ACCOUNTANT_SR TO USER USER3;
GRANT ROLE PRD_DBA TO USER USER4;


/*작업 테스트 및 검증*/
USE ROLE ACCOUNT_JR;
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTROY
WHERE QUERY_TYPE = 'GRANT';


