/* Snowflake 워크로드 */
 USE ROLE SYSADMIN;
 USE WAREHOUSE COMPUTE_WH;

 CREATE OR REPLACE DATABASE DEMO12_DB;
 CREATE OR REPLACE SCHEMA   CYBERSECURITY;
 ALTER SESSION SET USE_CACHED_RESULT = FALSE;   -- 캐시된 결과를 사용하지 않도록 세션을 변경하고 있다.
 
 /* WAREHOUSES 관리 권한*/
GRANT MANAGE WAREHOUSES ON ACCOUNT TO ROLE SYSADMIN;


/* 검색 최적화 서비스 & 클러스터링 비교 */


CREATE OR REPLACE TABLE BASETABLE 
AS
SELECT  *
FROM    SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM;

-- 클러스터링 예제에 사용할 테이블 복제 및 활성 
CREATE OR REPLACE TABLE CLUSTEREXAMPLE CLONE BASETABLE; -- 물리적이
ALTER TABLE CLUSTEREXAMPLE CLUSTER BY (L_SHIPDATE) ;


-- 클러스터링 확인
SELECT  SYSTEM$CLUSTERING_INFORMATION('CLUSTEREXAMPLE','(L_SHIPDATE)') ;
SELECT  SYSTEM$CLUSTERING_INFORMATION('BASETABLE','(L_SHIPDATE)') ;
 

-- 검색 최적화 예제에 사용할 테이블 복제
CREATE OR REPLACE TABLE OPTIMIZEEXAMPLE CLONE BASETABLE;
ALTER TABLE OPTIMIZEEXAMPLE ADD SEARCH OPTIMIZATION;

-- 확인 
SHOW TABLES LIKE '%EXAMPLE%';

SELECT * FROM BASETABLE LIMIT 1;

-- 프로파일러에서 확인 동등(=) 조건은 검색최적화 테이블이 더 효율적이다. 
SELECT * FROM BASETABLE WHERE L_ORDERKEY = '363617027';
SELECT * FROM CLUSTEREXAMPLE WHERE L_ORDERKEY = '363617027';


-- 프로파일러 확인
-- 클러스터 테이블
SELECT  *
FROM    CLUSTEREXAMPLE
WHERE  1=1
AND    L_SHIPDATE >= '1992-12-05' 
AND    L_SHIPDATE <  '1993-02-21'
AND    L_ORDERKEY = '363617027';

-- 검색최적화 테이블
SELECT  *
FROM    BASETABLE
WHERE  1=1
AND    L_SHIPDATE >= '1992-12-05' 
AND    L_SHIPDATE <  '1993-02-21'
AND    L_ORDERKEY = '363617027';









