/* Snowsight 예제 */

USE ROLE SYSADMIN;
USE DATABASE SNOWFLAKE_SAMPLE_DATA;
USE SCHEMA   SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL;



SELECT COUNT(*) 
FROM   SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.STORE_SALES;


/* 샘플링의 예 */

COMPUTE_WH

USE ROLE manage_wh_role;

SELECT  * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.STORE_SALES LIMIT 100;
SELECT  * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.STORE_SALES SAMPLE (100 ROWS);
SELECT  * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.STORE_SALES TABLESAMPLE SYSTEM (0.015);



/* 자동 통계 및 인터렉티브 결과 사용*/

SELECT * FROM CATALOG_RETURNS LIMIT 5000000;
SELECT * FROM CATALOG_RETURNS LIMIT 9999;

