/*지난 하루동안 현재 사용자가 실행한 모든 쿼리에 대한 세부 정보*/

USE ROLE ACCOUNTADMIN;
USE DATABASE SNOWFLAKE;

SELECT  *
FROM    TABLE(INFORMATION_SCHEMA.QUERY_HISTORY(
            DATEADD('day', -1, CURRENT_TIMESTAMP()),
            CURRENT_TIMESTAMP()))
ORDER BY TOTAL_ELAPSED_TIME DESC;


/* 해시 함수를 통해 평균 컴파일 시간 및 두 시간을 비교하기 위해 평균실행 시간 */
USE ROLE ACCOUNTADMIN;
USE DATABASE SNOWFLAKE;

SELECT  HASH(QUERY_TEXT), QUERY_TEXT, COUNT(*)
     ,  AVG(COMPILATION_TIME)
     ,  AVG(EXECUTION_TIME)
FROM    TABLE(INFORMATION_SCHEMA.QUERY_HISTORY(DATEADD('DAYS', -1, CURRENT_TIMESTAMP()), CURRENT_TIMESTAMP()))
GROUP BY HASH(QUERY_TEXT), QUERY_TEXT;


/* 클러스터 깊이 확인 */
USE ROLE ACCOUNTADMIN;
USE DATABASE SNOWFLAKE_SAMPLE_DATA;
USE SCHEMA TPCH_SF100;
SELECT SYSTEM$CLUSTERING_INFORMATION( 'CUSTOMER' , '(C_NATIONKEY )' );


/* 레코드 총 개수와 NATIONKEY 값의 개수르 얻기 위한 쿼리 */
USE ROLE ACCOUNTADMIN; 
USE DATABASE SNOWFLAKE_SAMPLE_DATA;
USE SCHEMA TPCH_SF100;

SELECT COUNT(DISTINCT C_NATIONKEY ) FROM CUSTOMER;
SELECT COUNT(C_NATIONKEY) FROM CUSTOMER; 


/* 선택성을 계산하기 위해 매우 낮은 선택성 값 0.000002의 값을 주는 다음 진술문  */
USE ROLE ACCOUNTADMIN ;
USE DATABASE SNOWFLAKE_SAMPLE_DATA; 
USE SCHEMA TPCH_SF100;

SELECT COUNT(DISTINCT C_NATIONKEY) / COUNT(C_NATIONKEY) FROM  CUSTOMER; 

SELECT C_NATIONKEY , COUNT(*) 
FROM  CUSTOMER 
GROUP BY C_NATIONKEY ;


/* 클러스터링 키 생성 */
ALTER TABLE <TABLE NAME> CLUSTER BY (column name(s)) ;


/* 검색 최적화 서비스 사용*/
ALTER TABLE [IF EXISTS] <TABLE NAME> ADD SEARCH OPTIMIZATION;
























       